#ifndef DYLIBLOAD_WRAPPER_AVCODEC
#define DYLIBLOAD_WRAPPER_AVCODEC
// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by hand for minimal FFmpeg avcodec support
//
#include <stdint.h>

#define avcodec_find_decoder avcodec_find_decoder_dylibloader_orig_avcodec
#define avcodec_alloc_context3 avcodec_alloc_context3_dylibloader_orig_avcodec
#define avcodec_free_context avcodec_free_context_dylibloader_orig_avcodec
#define avcodec_open2 avcodec_open2_dylibloader_orig_avcodec
#define avcodec_send_packet avcodec_send_packet_dylibloader_orig_avcodec
#define avcodec_receive_frame avcodec_receive_frame_dylibloader_orig_avcodec
#define av_packet_alloc av_packet_alloc_dylibloader_orig_avcodec
#define av_packet_free av_packet_free_dylibloader_orig_avcodec

#include <libavcodec/avcodec.h>

#undef avcodec_find_decoder
#undef avcodec_alloc_context3
#undef avcodec_free_context
#undef avcodec_open2
#undef avcodec_send_packet
#undef avcodec_receive_frame
#undef av_packet_alloc
#undef av_packet_free

#ifdef __cplusplus
extern "C" {
#endif

#define avcodec_find_decoder avcodec_find_decoder_dylibloader_wrapper_avcodec
#define avcodec_alloc_context3 avcodec_alloc_context3_dylibloader_wrapper_avcodec
#define avcodec_free_context avcodec_free_context_dylibloader_wrapper_avcodec
#define avcodec_open2 avcodec_open2_dylibloader_wrapper_avcodec
#define avcodec_send_packet avcodec_send_packet_dylibloader_wrapper_avcodec
#define avcodec_receive_frame avcodec_receive_frame_dylibloader_wrapper_avcodec
#define av_packet_alloc av_packet_alloc_dylibloader_wrapper_avcodec
#define av_packet_free av_packet_free_dylibloader_wrapper_avcodec

extern const AVCodec *(*avcodec_find_decoder_dylibloader_wrapper_avcodec)(enum AVCodecID id);
extern AVCodecContext *(*avcodec_alloc_context3_dylibloader_wrapper_avcodec)(const AVCodec *codec);
extern void (*avcodec_free_context_dylibloader_wrapper_avcodec)(AVCodecContext **avctx);
extern int (*avcodec_open2_dylibloader_wrapper_avcodec)(AVCodecContext *avctx, const AVCodec *codec, AVDictionary **options);
extern int (*avcodec_send_packet_dylibloader_wrapper_avcodec)(AVCodecContext *avctx, const AVPacket *avpkt);
extern int (*avcodec_receive_frame_dylibloader_wrapper_avcodec)(AVCodecContext *avctx, AVFrame *frame);
extern AVPacket *(*av_packet_alloc_dylibloader_wrapper_avcodec)(void);
extern void (*av_packet_free_dylibloader_wrapper_avcodec)(AVPacket **pkt);

int initialize_avcodec(int verbose);

#ifdef __cplusplus
}
#endif

#endif
