// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by hand for minimal FFmpeg avcodec support
//
#include <dlfcn.h>
#include <stdio.h>

#define avcodec_find_decoder avcodec_find_decoder_dylibloader_orig_avcodec
#define avcodec_alloc_context3 avcodec_alloc_context3_dylibloader_orig_avcodec
#define avcodec_free_context avcodec_free_context_dylibloader_orig_avcodec
#define avcodec_open2 avcodec_open2_dylibloader_orig_avcodec
#define avcodec_send_packet avcodec_send_packet_dylibloader_orig_avcodec
#define avcodec_receive_frame avcodec_receive_frame_dylibloader_orig_avcodec
#define av_packet_alloc av_packet_alloc_dylibloader_orig_avcodec
#define av_packet_free av_packet_free_dylibloader_orig_avcodec

#include <libavcodec/avcodec.h>

#undef avcodec_find_decoder
#undef avcodec_alloc_context3
#undef avcodec_free_context
#undef avcodec_open2
#undef avcodec_send_packet
#undef avcodec_receive_frame
#undef av_packet_alloc
#undef av_packet_free

#include <stdint.h>

const AVCodec *(*avcodec_find_decoder_dylibloader_wrapper_avcodec)(enum AVCodecID id);
AVCodecContext *(*avcodec_alloc_context3_dylibloader_wrapper_avcodec)(const AVCodec *codec);
void (*avcodec_free_context_dylibloader_wrapper_avcodec)(AVCodecContext **avctx);
int (*avcodec_open2_dylibloader_wrapper_avcodec)(AVCodecContext *avctx, const AVCodec *codec, AVDictionary **options);
int (*avcodec_send_packet_dylibloader_wrapper_avcodec)(AVCodecContext *avctx, const AVPacket *avpkt);
int (*avcodec_receive_frame_dylibloader_wrapper_avcodec)(AVCodecContext *avctx, AVFrame *frame);
AVPacket *(*av_packet_alloc_dylibloader_wrapper_avcodec)(void);
void (*av_packet_free_dylibloader_wrapper_avcodec)(AVPacket **pkt);

int initialize_avcodec(int verbose) {
	void *handle;
	char *error;
	handle = dlopen("libavcodec.so", RTLD_LAZY);
	if (!handle) {
		if (verbose) {
			fprintf(stderr, "%s\n", dlerror());
		}
		return 1;
	}
	dlerror();

// avcodec_find_decoder
	*(void **)(&avcodec_find_decoder_dylibloader_wrapper_avcodec) = dlsym(handle, "avcodec_find_decoder");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// avcodec_alloc_context3
	*(void **)(&avcodec_alloc_context3_dylibloader_wrapper_avcodec) = dlsym(handle, "avcodec_alloc_context3");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// avcodec_free_context
	*(void **)(&avcodec_free_context_dylibloader_wrapper_avcodec) = dlsym(handle, "avcodec_free_context");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// avcodec_open2
	*(void **)(&avcodec_open2_dylibloader_wrapper_avcodec) = dlsym(handle, "avcodec_open2");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// avcodec_send_packet
	*(void **)(&avcodec_send_packet_dylibloader_wrapper_avcodec) = dlsym(handle, "avcodec_send_packet");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// avcodec_receive_frame
	*(void **)(&avcodec_receive_frame_dylibloader_wrapper_avcodec) = dlsym(handle, "avcodec_receive_frame");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// av_packet_alloc
	*(void **)(&av_packet_alloc_dylibloader_wrapper_avcodec) = dlsym(handle, "av_packet_alloc");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// av_packet_free
	*(void **)(&av_packet_free_dylibloader_wrapper_avcodec) = dlsym(handle, "av_packet_free");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

	return 0;
}
