#ifndef DYLIBLOAD_WRAPPER_AVUTIL
#define DYLIBLOAD_WRAPPER_AVUTIL
// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by hand for minimal FFmpeg avutil support
//
#include <stdint.h>

#define av_frame_alloc av_frame_alloc_dylibloader_orig_avutil
#define av_frame_free av_frame_free_dylibloader_orig_avutil
#define av_frame_unref av_frame_unref_dylibloader_orig_avutil
#define av_image_get_buffer_size av_image_get_buffer_size_dylibloader_orig_avutil
#define av_image_fill_arrays av_image_fill_arrays_dylibloader_orig_avutil

#include <libavutil/frame.h>
#include <libavutil/imgutils.h>

#undef av_frame_alloc
#undef av_frame_free
#undef av_frame_unref
#undef av_image_get_buffer_size
#undef av_image_fill_arrays

#ifdef __cplusplus
extern "C" {
#endif

#define av_frame_alloc av_frame_alloc_dylibloader_wrapper_avutil
#define av_frame_free av_frame_free_dylibloader_wrapper_avutil
#define av_frame_unref av_frame_unref_dylibloader_wrapper_avutil
#define av_image_get_buffer_size av_image_get_buffer_size_dylibloader_wrapper_avutil
#define av_image_fill_arrays av_image_fill_arrays_dylibloader_wrapper_avutil

extern AVFrame *(*av_frame_alloc_dylibloader_wrapper_avutil)(void);
extern void (*av_frame_free_dylibloader_wrapper_avutil)(AVFrame **frame);
extern void (*av_frame_unref_dylibloader_wrapper_avutil)(AVFrame *frame);
extern int (*av_image_get_buffer_size_dylibloader_wrapper_avutil)(enum AVPixelFormat pix_fmt, int width, int height, int align);
extern int (*av_image_fill_arrays_dylibloader_wrapper_avutil)(uint8_t *dst_data[4], int dst_linesize[4], const uint8_t *src, enum AVPixelFormat pix_fmt, int width, int height, int align);

int initialize_avutil(int verbose);

#ifdef __cplusplus
}
#endif

#endif
