// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by hand for minimal FFmpeg avutil support
//
#include <dlfcn.h>
#include <stdio.h>

#define av_frame_alloc av_frame_alloc_dylibloader_orig_avutil
#define av_frame_free av_frame_free_dylibloader_orig_avutil
#define av_frame_unref av_frame_unref_dylibloader_orig_avutil
#define av_image_get_buffer_size av_image_get_buffer_size_dylibloader_orig_avutil
#define av_image_fill_arrays av_image_fill_arrays_dylibloader_orig_avutil

#include <libavutil/frame.h>
#include <libavutil/imgutils.h>

#undef av_frame_alloc
#undef av_frame_free
#undef av_frame_unref
#undef av_image_get_buffer_size
#undef av_image_fill_arrays

#include <stdint.h>

AVFrame *(*av_frame_alloc_dylibloader_wrapper_avutil)(void);
void (*av_frame_free_dylibloader_wrapper_avutil)(AVFrame **frame);
void (*av_frame_unref_dylibloader_wrapper_avutil)(AVFrame *frame);
int (*av_image_get_buffer_size_dylibloader_wrapper_avutil)(enum AVPixelFormat pix_fmt, int width, int height, int align);
int (*av_image_fill_arrays_dylibloader_wrapper_avutil)(uint8_t *dst_data[4], int dst_linesize[4], const uint8_t *src, enum AVPixelFormat pix_fmt, int width, int height, int align);

int initialize_avutil(int verbose) {
	void *handle;
	char *error;
	handle = dlopen("libavutil.so", RTLD_LAZY);
	if (!handle) {
		if (verbose) {
			fprintf(stderr, "%s\n", dlerror());
		}
		return 1;
	}
	dlerror();

// av_frame_alloc
	*(void **)(&av_frame_alloc_dylibloader_wrapper_avutil) = dlsym(handle, "av_frame_alloc");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// av_frame_free
	*(void **)(&av_frame_free_dylibloader_wrapper_avutil) = dlsym(handle, "av_frame_free");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// av_frame_unref
	*(void **)(&av_frame_unref_dylibloader_wrapper_avutil) = dlsym(handle, "av_frame_unref");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// av_image_get_buffer_size
	*(void **)(&av_image_get_buffer_size_dylibloader_wrapper_avutil) = dlsym(handle, "av_image_get_buffer_size");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// av_image_fill_arrays
	*(void **)(&av_image_fill_arrays_dylibloader_wrapper_avutil) = dlsym(handle, "av_image_fill_arrays");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

	return 0;
}
