#ifndef DYLIBLOAD_WRAPPER_SWSCALE
#define DYLIBLOAD_WRAPPER_SWSCALE
// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by hand for minimal FFmpeg swscale support
//
#include <stdint.h>

#define sws_getContext sws_getContext_dylibloader_orig_swscale
#define sws_scale sws_scale_dylibloader_orig_swscale
#define sws_freeContext sws_freeContext_dylibloader_orig_swscale

#include <libswscale/swscale.h>

#undef sws_getContext
#undef sws_scale
#undef sws_freeContext

#ifdef __cplusplus
extern "C" {
#endif

#define sws_getContext sws_getContext_dylibloader_wrapper_swscale
#define sws_scale sws_scale_dylibloader_wrapper_swscale
#define sws_freeContext sws_freeContext_dylibloader_wrapper_swscale

extern struct SwsContext *(*sws_getContext_dylibloader_wrapper_swscale)(int srcW, int srcH, enum AVPixelFormat srcFormat,
		int dstW, int dstH, enum AVPixelFormat dstFormat,
		int flags, SwsFilter *srcFilter,
		SwsFilter *dstFilter, const double *param);
extern int (*sws_scale_dylibloader_wrapper_swscale)(struct SwsContext *c, const uint8_t *const srcSlice[],
		const int srcStride[], int srcSliceY, int srcSliceH,
		uint8_t *const dst[], const int dstStride[]);
extern void (*sws_freeContext_dylibloader_wrapper_swscale)(struct SwsContext *swsContext);

int initialize_swscale(int verbose);

#ifdef __cplusplus
}
#endif

#endif
