// This file is generated. Do not edit!
// see https://github.com/hpvb/dynload-wrapper for details
// generated by hand for minimal FFmpeg swscale support
//
#include <dlfcn.h>
#include <stdio.h>

#define sws_getContext sws_getContext_dylibloader_orig_swscale
#define sws_scale sws_scale_dylibloader_orig_swscale
#define sws_freeContext sws_freeContext_dylibloader_orig_swscale

#include <libswscale/swscale.h>

#undef sws_getContext
#undef sws_scale
#undef sws_freeContext

#include <stdint.h>

struct SwsContext *(*sws_getContext_dylibloader_wrapper_swscale)(int srcW, int srcH, enum AVPixelFormat srcFormat,
		int dstW, int dstH, enum AVPixelFormat dstFormat,
		int flags, SwsFilter *srcFilter,
		SwsFilter *dstFilter, const double *param);
int (*sws_scale_dylibloader_wrapper_swscale)(struct SwsContext *c, const uint8_t *const srcSlice[],
		const int srcStride[], int srcSliceY, int srcSliceH,
		uint8_t *const dst[], const int dstStride[]);
void (*sws_freeContext_dylibloader_wrapper_swscale)(struct SwsContext *swsContext);

int initialize_swscale(int verbose) {
	void *handle;
	char *error;
	handle = dlopen("libswscale.so", RTLD_LAZY);
	if (!handle) {
		if (verbose) {
			fprintf(stderr, "%s\n", dlerror());
		}
		return 1;
	}
	dlerror();

// sws_getContext
	*(void **)(&sws_getContext_dylibloader_wrapper_swscale) = dlsym(handle, "sws_getContext");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// sws_scale
	*(void **)(&sws_scale_dylibloader_wrapper_swscale) = dlsym(handle, "sws_scale");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

// sws_freeContext
	*(void **)(&sws_freeContext_dylibloader_wrapper_swscale) = dlsym(handle, "sws_freeContext");
	if (verbose) {
		error = dlerror();
		if (error != NULL) {
			fprintf(stderr, "%s\n", error);
		}
	}

	return 0;
}
